In [1]:
import polars as pl
import time

## Big Data e Processamento Otimizado com Python II

### Manipulação do Parquet e StringCache

In [2]:
inicial = (
    pl.scan_parquet("../Aula12/202501_NovoBolsaFamilia_POLARS.parquet")
    .rename({
        'M�S COMPET�NCIA': 'MES_COMPETENCIA',
        'M�S REFER�NCIA': 'MES_REFERENCIA',
        'C�DIGO MUNIC�PIO SIAFI': 'CODIGO_MUNICIPIO_SIAFI',
        'NOME MUNIC�PIO': 'NOME_MUNICIPIO',
    })
    .with_columns(
        pl.col("VALOR PARCELA")
        .str.replace(",", ".")   
        .cast(pl.Float64)          
    )
)

display(inicial.collect())

shape: (20_500_422, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202501     ┆ 202308     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202309     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202310     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202311     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202312     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202501     ┆ 202501     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 1664089069 ┆ ZEIA DE   ┆ 750.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 1          ┆ SOUZA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LUCIO     ┆           │
│ 202501     ┆ 202501     ┆ TO  ┆ 9643       ┆ … ┆ ***.273.19 ┆ 2064488199 ┆ ZENILDE   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 7          ┆ ALVES DOS ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202501     ┆ 202501     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 1905866197 ┆ ZENOLIA   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ RAMOS DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CARVALH…  ┆           │
│ 202501     ┆ 202501     ┆ TO  ┆ 9643       ┆ … ┆ ***.822.65 ┆ 2091926382 ┆ ZILMA     ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 2          ┆ ALVES DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BARROS    ┆           │
│ 202501     ┆ 202501     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 2050119994 ┆ ZULEIDE   ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ DA SILVA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ E SILVA   ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

### Filtros
Para selecionar linhas baseadas em condições lógicas (semelhante ao WHERE do SQL).

In [3]:
# Filtro Simples: Apenas beneficiários do Rio de Janeiro
q_rj = inicial.filter(pl.col("UF") == "RJ")

# Filtro Composto (E / OU): RJ e valor maior que 800
q_rj_alto = inicial.filter(
    (pl.col("UF") == "RJ") & (pl.col("VALOR PARCELA") > 800)
)

# Filtro com Lista (IS IN): Apenas estados do Sudeste
q_sudeste = inicial.filter(
    pl.col("UF").is_in(["SP", "RJ", "MG", "ES"])
)

display(q_rj.collect())
display(q_rj_alto.collect())
display(q_sudeste.collect())

shape: (1_577_414, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202501     ┆ 202406     ┆ RJ  ┆ 5869       ┆ … ┆            ┆ 1700915279 ┆ PAULO     ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ DUARTE    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ JUNIOR    ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 5801       ┆ … ┆            ┆ 1390779098 ┆ CAMILA    ┆ 800.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 6          ┆ INACIO    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GOMES     ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 5803       ┆ … ┆ ***.319.33 ┆ 1659029128 ┆ SIRLEA    ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 5          ┆ ALVES     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CORREA    ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 5807       ┆ … ┆            ┆ 2122689137 ┆ EMANUELLE ┆ 750.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 5          ┆ ARAUJO DA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 5807       ┆ … ┆ ***.924.68 ┆ 1323233462 ┆ FABIANA   ┆ 800.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 7          ┆ PEREIRA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ VIEIR…    ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆            ┆ 1314378560 ┆ ZITIELEN  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CAETANO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BIT…      ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.546.28 ┆ 2372406310 ┆ ZIULANDA  ┆ 300.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 1          ┆ NICOLAU   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.233.60 ┆ 2061170679 ┆ ZULEICA   ┆ 350.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 7          ┆ APARECIDA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ALVES     ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.649.99 ┆ 2003805509 ┆ ZULEICA   ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 5          ┆ FLORENTIN ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ O DA      ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.616.18 ┆ 1276120760 ┆ ZULEIGA   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 4          ┆ FERREIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DE        ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (188_807, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202501     ┆ 202407     ┆ RJ  ┆ 5813       ┆ … ┆ ***.820.61 ┆ 1620414579 ┆ CAMILA    ┆ 1110.0    │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 8          ┆ RAFAELA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 5819       ┆ … ┆ ***.885.12 ┆ 1638123429 ┆ LUDIMILLA ┆ 1202.0    │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 7          ┆ FERREIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DE SOUZA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GO…       ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 5819       ┆ … ┆ ***.741.86 ┆ 1668780930 ┆ MYLENA    ┆ 1076.0    │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 0          ┆ MARTINS   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CORREA    ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 772        ┆ … ┆ ***.382.55 ┆ 1616903208 ┆ BARBARA   ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 2          ┆ BORGES    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ FERREIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ANDRAD…   ┆           │
│ 202501     ┆ 202407     ┆ RJ  ┆ 5833       ┆ … ┆ ***.188.24 ┆ 2070243925 ┆ FLAVIA    ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 2          ┆ LEITE DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆            ┆ 1370780403 ┆ YURAIMA   ┆ 950.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ JOSEFINA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ARREAZA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ROCA      ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.948.74 ┆ 1379054077 ┆ ZAILANE   ┆ 850.0     │
│            ┆            ┆     ┆            ┆   ┆ 3-**       ┆ 2          ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CAMAR…    ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.921.20 ┆ 1289201056 ┆ ZAINE ALI ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 1          ┆ SEIFEDDIN ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ E         ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.936.33 ┆ 2077635202 ┆ ZEZABEL   ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 9          ┆ ESTEVAO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ COSTA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ALMEI…    ┆           │
│ 202501     ┆ 202501     ┆ RJ  ┆ 5925       ┆ … ┆ ***.402.27 ┆ 1667150444 ┆ ZILMARA   ┆ 1294.0    │
│            ┆            ┆     ┆            ┆   ┆ 7-**       ┆ 0          ┆ LEAL      ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CLAUDIO   ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (5_906_411, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202501     ┆ 202308     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202309     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202310     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202311     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202312     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202501     ┆ 202501     ┆ SP  ┆ 2973       ┆ … ┆            ┆ 2049170098 ┆ VANDERSON ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ DIOGO DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202501     ┆ 202501     ┆ SP  ┆ 2973       ┆ … ┆ ***.696.97 ┆ 1652889109 ┆ VANILDE   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 6          ┆ ARMINDO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202501     ┆ 202501     ┆ SP  ┆ 2973       ┆ … ┆ ***.960.04 ┆ 1658316052 ┆ WELINGTON ┆ 450.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 9          ┆ LUCAS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BATISTA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ COELHO    ┆           │
│ 202501     ┆ 202501     ┆ SP  ┆ 2973       ┆ … ┆ ***.074.43 ┆ 2043678790 ┆ WESLEY    ┆ 950.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 8          ┆ JUNIOR DA ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SIMPLIC…  ┆           │
│ 202501     ┆ 202501     ┆ SP  ┆ 2973       ┆ … ┆            ┆ 2138499203 ┆ YASMIM    ┆ 900.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 2          ┆ PISTOLATO ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MECIANO   ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

### Seleção e Exclusão
Para escolher ou remover colunas específicas.

In [4]:
# Selecionar apenas colunas de interesse
q_simples = inicial.select(["UF", "NOME_MUNICIPIO", "VALOR PARCELA"])

# .drop() remove as colunas listadas
q_sem_codigos = inicial.drop(["CODIGO_MUNICIPIO_SIAFI", "NIS FAVORECIDO"])

# Seleciona tudo (implícito) excluindo as colunas listadas
q_sem_codigos = inicial.select(pl.exclude(["CODIGO_MUNICIPIO_SIAFI", "NIS FAVORECIDO"]))

display(q_simples.collect())
display(q_sem_codigos.collect())

shape: (20_500_422, 3)
┌─────┬────────────────┬───────────────┐
│ UF  ┆ NOME_MUNICIPIO ┆ VALOR PARCELA │
│ --- ┆ ---            ┆ ---           │
│ str ┆ str            ┆ f64           │
╞═════╪════════════════╪═══════════════╡
│ SP  ┆ SANTOS         ┆ 650.0         │
│ SP  ┆ SANTOS         ┆ 650.0         │
│ SP  ┆ SANTOS         ┆ 650.0         │
│ SP  ┆ SANTOS         ┆ 650.0         │
│ SP  ┆ SANTOS         ┆ 650.0         │
│ …   ┆ …              ┆ …             │
│ TO  ┆ XAMBIOA        ┆ 750.0         │
│ TO  ┆ XAMBIOA        ┆ 600.0         │
│ TO  ┆ XAMBIOA        ┆ 600.0         │
│ TO  ┆ XAMBIOA        ┆ 600.0         │
│ TO  ┆ XAMBIOA        ┆ 650.0         │
└─────┴────────────────┴───────────────┘

shape: (20_500_422, 7)
┌────────────────┬────────────────┬─────┬────────────────┬───────────────┬───────────────┬─────────┐
│ MES_COMPETENCI ┆ MES_REFERENCIA ┆ UF  ┆ NOME_MUNICIPIO ┆ CPF           ┆ NOME          ┆ VALOR   │
│ A              ┆ ---            ┆ --- ┆ ---            ┆ FAVORECIDO    ┆ FAVORECIDO    ┆ PARCELA │
│ ---            ┆ i64            ┆ str ┆ str            ┆ ---           ┆ ---           ┆ ---     │
│ i64            ┆                ┆     ┆                ┆ str           ┆ str           ┆ f64     │
╞════════════════╪════════════════╪═════╪════════════════╪═══════════════╪═══════════════╪═════════╡
│ 202501         ┆ 202308         ┆ SP  ┆ SANTOS         ┆ ***.085.106-* ┆ FERNANDA      ┆ 650.0   │
│                ┆                ┆     ┆                ┆ *             ┆ RAMOS         ┆         │
│                ┆                ┆     ┆                ┆               ┆ TEIXEIRA      ┆         │
│ 202501         ┆ 202309         ┆ SP  ┆ SANTOS         ┆ ***.085.106-* ┆ FERNANDA      ┆ 650.0   │
│                ┆                ┆     ┆                ┆ *             ┆ RAMOS         ┆         │
│                ┆                ┆     ┆                ┆               ┆ TEIXEIRA      ┆         │
│ 202501         ┆ 202310         ┆ SP  ┆ SANTOS         ┆ ***.085.106-* ┆ FERNANDA      ┆ 650.0   │
│                ┆                ┆     ┆                ┆ *             ┆ RAMOS         ┆         │
│                ┆                ┆     ┆                ┆               ┆ TEIXEIRA      ┆         │
│ 202501         ┆ 202311         ┆ SP  ┆ SANTOS         ┆ ***.085.106-* ┆ FERNANDA      ┆ 650.0   │
│                ┆                ┆     ┆                ┆ *             ┆ RAMOS         ┆         │
│                ┆                ┆     ┆                ┆               ┆ TEIXEIRA      ┆         │
│ 202501         ┆ 202312         ┆ SP  ┆ SANTOS         ┆ ***.085.106-* ┆ FERNANDA      ┆ 650.0   │
│                ┆                ┆     ┆                ┆ *             ┆ RAMOS         ┆         │
│                ┆                ┆     ┆                ┆               ┆ TEIXEIRA      ┆         │
│ …              ┆ …              ┆ …   ┆ …              ┆ …             ┆ …             ┆ …       │
│ 202501         ┆ 202501         ┆ TO  ┆ XAMBIOA        ┆               ┆ ZEIA DE SOUZA ┆ 750.0   │
│                ┆                ┆     ┆                ┆               ┆ LUCIO         ┆         │
│ 202501         ┆ 202501         ┆ TO  ┆ XAMBIOA        ┆ ***.273.191-* ┆ ZENILDE ALVES ┆ 600.0   │
│                ┆                ┆     ┆                ┆ *             ┆ DOS SANTOS    ┆         │
│ 202501         ┆ 202501         ┆ TO  ┆ XAMBIOA        ┆               ┆ ZENOLIA RAMOS ┆ 600.0   │
│                ┆                ┆     ┆                ┆               ┆ DA SILVA      ┆         │
│                ┆                ┆     ┆                ┆               ┆ CARVALH…      ┆         │
│ 202501         ┆ 202501         ┆ TO  ┆ XAMBIOA        ┆ ***.822.651-* ┆ ZILMA ALVES   ┆ 600.0   │
│                ┆                ┆     ┆                ┆ *             ┆ DE BARROS     ┆         │
│ 202501         ┆ 202501         ┆ TO  ┆ XAMBIOA        ┆               ┆ ZULEIDE DA    ┆ 650.0   │
│                ┆                ┆     ┆                ┆               ┆ SILVA E SILVA ┆         │
└────────────────┴────────────────┴─────┴────────────────┴───────────────┴───────────────┴─────────┘

### Condicionais
Criar novas colunas com base em lógica (semelhante ao IF do Excel ou CASE WHEN do SQL).

In [5]:
# Categorizar o pagamento
q_categoria = inicial.with_columns(
    pl.when(pl.col("VALOR PARCELA") >= 900)
    .then(pl.lit("Alto Valor"))
    .when(pl.col("VALOR PARCELA") > 600)
    .then(pl.lit("Médio Valor"))
    .otherwise(pl.lit("Básico"))
    .alias("CATEGORIA_PAGAMENTO")
)

display(q_categoria.select(["VALOR PARCELA", "CATEGORIA_PAGAMENTO"]).collect())

shape: (20_500_422, 2)
┌───────────────┬─────────────────────┐
│ VALOR PARCELA ┆ CATEGORIA_PAGAMENTO │
│ ---           ┆ ---                 │
│ f64           ┆ str                 │
╞═══════════════╪═════════════════════╡
│ 650.0         ┆ Médio Valor         │
│ 650.0         ┆ Médio Valor         │
│ 650.0         ┆ Médio Valor         │
│ 650.0         ┆ Médio Valor         │
│ 650.0         ┆ Médio Valor         │
│ …             ┆ …                   │
│ 750.0         ┆ Médio Valor         │
│ 600.0         ┆ Básico              │
│ 600.0         ┆ Básico              │
│ 600.0         ┆ Básico              │
│ 650.0         ┆ Médio Valor         │
└───────────────┴─────────────────────┘

In [6]:
# Partindo do LazyFrame 'q_categoria' já criado
q_analise_categoria = (
    q_categoria
    .group_by("CATEGORIA_PAGAMENTO")
    .agg([
        pl.len().alias("total_beneficiarios"),
        pl.col("VALOR PARCELA").mean().alias("media_pagamento"),
        pl.col("VALOR PARCELA").min().alias("menor_pagamento"),
        pl.col("VALOR PARCELA").max().alias("maior_pagamento"),
        pl.col("VALOR PARCELA").sum().alias("total_investido")
    ])
    .sort("media_pagamento", descending=True)
)

display(q_analise_categoria.collect())

shape: (3, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ CATEGORIA_PAGA ┆ total_benefici ┆ media_pagament ┆ menor_pagamen ┆ maior_pagamen ┆ total_investi │
│ MENTO          ┆ arios          ┆ o              ┆ to            ┆ to            ┆ do            │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ str            ┆ u32            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ Alto Valor     ┆ 2103126        ┆ 1038.537427    ┆ 900.0         ┆ 3938.0        ┆ 2.1842e9      │
│ Médio Valor    ┆ 9657874        ┆ 724.877575     ┆ 601.0         ┆ 898.0         ┆ 7.0008e9      │
│ Básico         ┆ 8739422        ┆ 520.723108     ┆ 25.0          ┆ 600.0         ┆ 4.5508e9      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

### Fatiamento
Para pegar "pedaços" dos dados. No modo Lazy, o slice é muito eficiente pois o Polars lê apenas o necessário do disco.

In [7]:
# Pegar as primeiras 10 linhas
q_head = inicial.head(10)

# Pegar da linha 100 até a 150 (offset 100, length 50)
q_meio = inicial.slice(100, 50)

display(q_head.collect())
display(q_meio.collect())

shape: (10, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202501     ┆ 202308     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202309     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202310     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202311     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202312     ┆ SP  ┆ 7071       ┆ … ┆ ***.085.10 ┆ 2064389044 ┆ FERNANDA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ RAMOS     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ TEIXEIRA  ┆           │
│ 202501     ┆ 202401     ┆ CE  ┆ 1389       ┆ … ┆ ***.854.49 ┆ 1302405519 ┆ IRENICE   ┆ 750.0     │
│            ┆            ┆     ┆            ┆   ┆ 3-**       ┆ 2          ┆ CAMELO    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ VALETE    ┆           │
│ 202501     ┆ 202401     ┆ PA  ┆ 479        ┆ … ┆ ***.868.79 ┆ 1602513240 ┆ ANTONIA   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 3          ┆ ELIZANA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202501     ┆ 202401     ┆ SP  ┆ 6313       ┆ … ┆ ***.972.79 ┆ 1331023985 ┆ DAMARIS   ┆ 800.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 2          ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
│ 202501     ┆ 202401     ┆ SP  ┆ 6313       ┆ … ┆ ***.696.85 ┆ 2021744274 ┆ PRISCILA  ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 3          ┆ HELENA DE ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LIMA      ┆           │
│ 202501     ┆ 202401     ┆ SP  ┆ 6887       ┆ … ┆ ***.295.29 ┆ 1601742565 ┆ ERICA     ┆ 1010.0    │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 0          ┆ CRISTINA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ RIBEIRO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILV…  ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (50, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MES_COMPET ┆ MES_REFERE ┆ UF  ┆ CODIGO_MUN ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ENCIA      ┆ NCIA       ┆ --- ┆ ICIPIO_SIA ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ FI         ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ f64       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202501     ┆ 202406     ┆ MA  ┆ 937        ┆ … ┆ ***.452.78 ┆ 1618506682 ┆ GISELIA   ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 3-**       ┆ 4          ┆ DE        ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ANDRADE   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ LIMA      ┆           │
│ 202501     ┆ 202406     ┆ MA  ┆ 949        ┆ … ┆            ┆ 2092777094 ┆ MARINALDO ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 0          ┆ NUNES     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ COSTA     ┆           │
│ 202501     ┆ 202406     ┆ MG  ┆ 4031       ┆ … ┆ ***.970.32 ┆ 2034523949 ┆ TALYSSON  ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 5          ┆ DE SOUZA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ESTEVAM   ┆           │
│ 202501     ┆ 202406     ┆ MG  ┆ 4123       ┆ … ┆ ***.510.06 ┆ 1303511009 ┆ CAMILA    ┆ 700.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 2          ┆ CUNHA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ OLIVEIRA  ┆           │
│ 202501     ┆ 202406     ┆ MG  ┆ 4265       ┆ … ┆ ***.049.55 ┆ 1662850438 ┆ TAILANI   ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 6-**       ┆ 8          ┆ FERREIRA  ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202501     ┆ 202406     ┆ RJ  ┆ 5869       ┆ … ┆            ┆ 1700915279 ┆ PAULO     ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ DUARTE    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ JUNIOR    ┆           │
│ 202501     ┆ 202406     ┆ RN  ┆ 1779       ┆ … ┆ ***.718.34 ┆ 1261587064 ┆ GEYSE     ┆ 650.0     │
│            ┆            ┆     ┆            ┆   ┆ 4-**       ┆ 7          ┆ MONTEIRO  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202501     ┆ 202406     ┆ RO  ┆ 3          ┆ … ┆ ***.375.10 ┆ 2034582398 ┆ NELSON    ┆ 600.0     │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 7          ┆ GARCIA    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SOBRINHO  ┆           │
│ 202501     ┆ 202406     ┆ SC  ┆ 8179       ┆ … ┆ ***.302.46 ┆ 2073928537 ┆ LENORA DA ┆ 950.0     │
│            ┆            ┆     ┆            ┆   ┆ 9-**       ┆ 2          ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ KRUEGER   ┆           │
│ 202501     ┆ 202406     ┆ SC  ┆ 8351       ┆ … ┆ ***.276.35 ┆ 1272184072 ┆ NILDA     ┆ 325.0     │
│            ┆            ┆     ┆            ┆   ┆ 9-**       ┆ 1          ┆ MULLER    ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [8]:
# Recorte de linhas specíficas (ex: linha 0, 10 e 50)
q_recorte_indices = (
    inicial
    .with_row_index("id_linha")  # Cria uma coluna temporária com o número da linha
    .filter(pl.col("id_linha").is_in([0, 10, 50])) # Filtra pelos números desejados
    .select(["UF", "NOME_MUNICIPIO"]) # Seleciona as colunas
)

display(q_recorte_indices.collect())

shape: (3, 2)
┌─────┬────────────────┐
│ UF  ┆ NOME_MUNICIPIO │
│ --- ┆ ---            │
│ str ┆ str            │
╞═════╪════════════════╡
│ SP  ┆ SANTOS         │
│ SP  ┆ SANTOS         │
│ PR  ┆ GUARAPUAVA     │
└─────┴────────────────┘

### Agrupamento Avançado (group_by + agg)

In [9]:
q_stats_mun = (
    inicial.group_by("NOME_MUNICIPIO")
    .agg([
        pl.len().alias("total_familias"),  # Contagem rápida
        pl.col("VALOR PARCELA").sum().alias("total_repassado"),
        pl.col("VALOR PARCELA").max().alias("maior_pagamento"),
        pl.col("UF").first().alias("uf_origem") # Mantém a UF do municipio
    ])
    .sort("total_repassado", descending=True)
)

display(q_stats_mun.collect())

shape: (5_291, 5)
┌─────────────────────┬────────────────┬─────────────────┬─────────────────┬───────────┐
│ NOME_MUNICIPIO      ┆ total_familias ┆ total_repassado ┆ maior_pagamento ┆ uf_origem │
│ ---                 ┆ ---            ┆ ---             ┆ ---             ┆ ---       │
│ str                 ┆ u32            ┆ f64             ┆ f64             ┆ str       │
╞═════════════════════╪════════════════╪═════════════════╪═════════════════╪═══════════╡
│ SAO PAULO           ┆ 679740         ┆ 4.4679095e8     ┆ 3322.0          ┆ SP        │
│ RIO DE JANEIRO      ┆ 499084         ┆ 3.27039464e8    ┆ 3072.0          ┆ RJ        │
│ FORTALEZA           ┆ 324273         ┆ 2.09478569e8    ┆ 2562.0          ┆ CE        │
│ SALVADOR            ┆ 299582         ┆ 1.93376165e8    ┆ 2804.0          ┆ BA        │
│ MANAUS              ┆ 261304         ┆ 1.80283025e8    ┆ 2996.0          ┆ AM        │
│ …                   ┆ …              ┆ …               ┆ …               ┆ …         │
│ MONTAURI            ┆ 11             ┆ 6650.0          ┆ 1000.0          ┆ RS        │
│ CORONEL PILAR       ┆ 9              ┆ 6469.0          ┆ 1444.0          ┆ RS        │
│ BRACO DO TROMBUDO   ┆ 13             ┆ 6287.0          ┆ 651.0           ┆ SC        │
│ TRES ARROIOS        ┆ 10             ┆ 6110.0          ┆ 1060.0          ┆ RS        │
│ SAO DOMINGOS DO SUL ┆ 7              ┆ 5740.0          ┆ 1344.0          ┆ RS        │
└─────────────────────┴────────────────┴─────────────────┴─────────────────┴───────────┘

### StringCache e Otimização de CPU

Como estamos na fase de pré-processamento de Big Data, precisamos conectar o conceito de hardware com o código.

#### O Problema da String: 

Textos são "pesadas" para a CPU processar. Comparar a palavra "RIO DE JANEIRO" com "RIO DE JANEIRO" exige verificar letra por letra. Isso ocupa muito espaço na memória Cache (L1/L2/L3) do processador, que é ultrarrápida mas muito pequena.

Uma solução? Em vez de guardar a palavra "SP" milhões de vezes, o computador cria um dicionário: 0 = SP, 1 = RJ. Ele processa números (inteiros), o que é mais rápido para a CPU.

O **StringCache** do Polars: Garante que esse dicionário seja GLOBAL.

- *Sem StringCache*: Se você tiver dois DataFrames, "SP" pode ser o código 0 no primeiro e o código 5 no segundo. Isso impede junções (joins) corretas sem recriar os dados.

- *Com StringCache*: "SP" será o código 0 em qualquer operação enquanto o cache estiver ativo.

#### Vantagens Técnicas:

Uso de Memória RAM: Em colunas com *baixa cardinalidade* (muita repetição, como UF ou NOME_MUNICIPIO), o uso de memória cai drasticamente.

Velocidade em Joins e Agrupamentos: Agrupar por inteiros é muito mais rápido do que por strings para a lógica computacional.

In [10]:
print("=== TESTE 1: Processamento SEM StringCache ===")
start_1 = time.time()

q_sem_cache = (
    pl.scan_parquet("../Aula12/202501_NovoBolsaFamilia_POLARS.parquet")
    .rename({
        'M�S COMPET�NCIA': 'MES_COMPETENCIA',
        'M�S REFER�NCIA': 'MES_REFERENCIA',
        'C�DIGO MUNIC�PIO SIAFI': 'CODIGO_MUNICIPIO_SIAFI',
        'NOME MUNIC�PIO': 'NOME_MUNICIPIO',
    })
    .with_columns(
        pl.col("VALOR PARCELA")
        .str.replace(",", ".")   
        .cast(pl.Float64)          
    )
    .group_by(["UF", "NOME_MUNICIPIO"]) 
    .agg([
        pl.col("VALOR PARCELA").mean().alias("media"),
        pl.col("VALOR PARCELA").std().alias("desvio")
    ])
    .sort("media", descending=True)
)

df_1 = q_sem_cache.collect()
end_1 = time.time()
tempo_sem = end_1 - start_1
print(f"Tempo SEM Cache: {tempo_sem:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_1['UF'].estimated_size()} bytes\n")

=== TESTE 1: Processamento SEM StringCache ===
Tempo SEM Cache: 0.9173 segundos
Uso de memória estimado (coluna UF): 11140 bytes

In [11]:
print("=== TESTE 2: Processamento COM StringCache ===")
# O StringCache funciona como um contexto (with)
with pl.StringCache():
    start_2 = time.time()
    
    q_com_cache = (
    pl.scan_parquet("../Aula12/202501_NovoBolsaFamilia_POLARS.parquet")
    .rename({
        'M�S COMPET�NCIA': 'MES_COMPETENCIA',
        'M�S REFER�NCIA': 'MES_REFERENCIA',
        'C�DIGO MUNIC�PIO SIAFI': 'CODIGO_MUNICIPIO_SIAFI',
        'NOME MUNIC�PIO': 'NOME_MUNICIPIO',
    })
    .with_columns(
        pl.col("VALOR PARCELA")
        .str.replace(",", ".")   
        .cast(pl.Float64)          
    )
    .group_by(["UF", "NOME_MUNICIPIO"]) 
    .agg([
        pl.col("VALOR PARCELA").mean().alias("media"),
        pl.col("VALOR PARCELA").std().alias("desvio")
    ])
    .sort("media", descending=True)
)
    
    df_2 = q_com_cache.collect() # Ação!
    end_2 = time.time()

tempo_com = end_2 - start_2
print(f"Tempo COM Cache: {tempo_com:.4f} segundos")
print(f"Uso de memória estimado (coluna UF): {df_2['UF'].estimated_size()} bytes\n")

=== TESTE 2: Processamento COM StringCache ===
Tempo COM Cache: 1.0065 segundos
Uso de memória estimado (coluna UF): 11140 bytes